### PR TITLE
Get rid of flask-oidc lib, rewrite okta-hosted-login app.

### PR DESCRIPTION
**Pull request by serhiibuniak-okta**

### CODE REVIEW

**Comment by bretterer** [comment]
Pending publish of JWT Verifier

**Comment by bmike78** [comment]
@bretterer, any update on when JWT Verifier will be ready to go?

**Comment by bretterer** [comment]
@bmike78 we are still in the process of checking off our internal boxes before we can make the verifier public.  I do not currently have a date that I can give you for this but we will update here when we know more

**Comment by bmike78** [comment]
@bretterer any update?

**Comment by serhiibuniak-okta** [comment]
@bmike78 Hi, the work is still in progress, but it is expected to be finished soon. We'll keep you posted.

**Review by laura-rodriguez — APPROVED** [review]

**Review by laurarodriguez-okta — APPROVED** [review]

**Pull request merged**
